### ISSUE TITLE
Brutalis Dreadnought - Brutalis Charge ability doesn't work

### ISSUE THREAD

**Issue by eMarchenko** [korzxd/UnitCrunch-data-exports#10] opened 2023-10-18 09:28 UTC
Brutalis Charge ability is implemented as a melee weapon with N/A weapon skill. As a result, it never hits. 
Can be fixed by adding "Always hits"/"TORRENT" ability to this weapon.

Probably applicable to other non-attack damage abilities, I didn't check.

**Comment by korzxd** [comment] 2023-10-19 08:47
Thanks for pointing this out. I just checked through all the other non-attack abilities and they're working as intended, the `Brutalis Charge` is the only one missing the `TORRENT` weapon ability.

I will have this fixed with the next update which should happen when i get public access to the Codex. 👍

**Comment by dixhuit** [comment] 2023-10-19 11:16
It might be less confusing to add an "Always hit" ability to "Brutalis Charge" as opposed to "TORRENT". I know they do the same thing but "TORRENT" is an actual USR which isn't really involved here. You can disable the ability alias using the checkbox when editing the ability (see screen grab).

![image](https://github.com/korzxd/UnitCrunch-data-exports/assets/6885065/eb4cbd9c-dcb9-4426-a295-2ebb1ebcb387)

**Comment by korzxd** [comment] 2023-10-20 08:01
Good shout! I forgot about the Alias checkbox, i'll make sure to uncheck that on the other non-attack abilities as well.

**Closed as completed** 2023-11-30 09:03 UTC
